#! /usr/bin/ruby

# https://developers.google.com/calendar/create-events
# https://developers.google.com/calendar/v3/reference/events
# https://tools.ietf.org/html/rfc5545#section-3.8.5
# https://icalendar.org/rrule-tool.html

# @remember: should limit image file size
# @remember: should allow event to be from 11pm - 12am (maybe auto set to 11:59)

events = JSON.parse($background_task_params[:events])
google_calendar_id = $background_task_params[:google_calendar_id]
google_id = $background_task_params[:google_id] || events[0]['google_id']

delete_google_calendar_events(events,google_calendar_id,google_id)
