#! /usr/bin/ruby

require_relative '../lib/tom_calendar.rb'
require 'time'
require 'tzinfo'

# https://developers.google.com/calendar/create-events
# https://developers.google.com/calendar/v3/reference/events
# https://tools.ietf.org/html/rfc5545#section-3.8.5
# https://icalendar.org/rrule-tool.html

# @remember: should limit image file size
# @remember: should allow event to be from 11pm - 12am (maybe auto set to 11:59)

events = JSON.parse(ARGV[0])
google_calendar_id = ARGV[1]
google_id = ARGV[2] || events[0]['google_id']
if !google_id || (google_id == '') || (google_id == ' ')
  google_id = events[0]['google_id']
end

dynamodb              = Aws::DynamoDB::Client.new(region: ENV['AWS_REGION'])
google_authorizer     = get_google_authorizer(dynamodb)
service               = Google::Apis::CalendarV3::CalendarService.new
service.authorization = google_authorizer.get_credentials(google_id)
service.client_options.application_name = 'TomCalendar'.freeze

events.each do |event|
  result = service.list_events(google_calendar_id, private_extended_property: "tomcalendar_id=#{event['google_id']}-#{event['title']}")
  result.items.each do |google_event|
    service.delete_event(google_calendar_id, google_event.id)
  end
end
