#! /usr/bin/ruby

require_relative '../lib/tom_calendar.rb'


# check header for valid X-Requested-With?

user_id = 'default'

dynamodb = Aws::DynamoDB::Client.new(region: ENV['AWS_REGION'])

google_authorizer = get_google_authorizer(dynamodb)
credentials = nil#google_authorizer.get_credentials(user_id)

if credentials.nil?
  authorization_code = ARGF.first

  #credentials = google_authorizer.get_and_store_credentials_from_code(user_id: user_id, code: authorization_code)
  credentials = google_authorizer.get_credentials_from_code(user_id: user_id, code: authorization_code)
end

if credentials.nil?
  puts "Content-type: text/html\n\n"
  puts 'failed'
else
  puts "Content-type: text/html\n\n"
  puts "access_token: #{credentials.access_token}!!!!!!!!!refresh_token: #{credentials.refresh_token}!!!!!!!!!!!!!!!!id_token: #{credentials.id_token}"
end



