#! /usr/bin/ruby

require_relative '../lib/tom_calendar.rb'

#puts 'Content-type: text/html'

# apache environment variables
#ENV.keys.each {|key| puts key.to_s + "\n"}
#puts "REQUEST_URI: #{ENV['REQUEST_URI']}"

# stdin for handling post requests
#ARGF.each do |line|
#    puts "line: #{line}"
#end


dynamodb = Aws::DynamoDB::Client.new(region: ENV['AWS_REGION'])
TomCalendarTokenStore.new(dynamodb)


puts "Content-type: text/html\n\n"
authorization_code = ENV['QUERY_STRING']
puts authorization_code

# use regex to parse "code" param from query string






=begin
dynamodb = Aws::DynamoDB::Client.new(region: ENV['AWS_REGION'])

item = {
	creator_username: 'tom',
  title: "test_event #{Time.now}",
}

params = {
	table_name: 'Events',
  #item: item
	key: { creator_username: 'tom',
         title: 'test_event 2020-07-01 12:04:41 +0000'
  }
}

# add item
begin
  dynamodb.put_item(params)
  puts 'Added Event'
rescue  Aws::DynamoDB::Errors::ServiceError => error
  puts 'Unable to add Event:'
  puts error.message
end
=end

