#! /usr/bin/ruby

require_relative '../lib/tom_calendar.rb'

result = { needed_to_create: false }

cookie_session_id = ENV['HTTP_COOKIE']&.split(';')&.find{ |cookie| cookie.match?('session_id') }&.sub('session_id=','')&.strip
cookie_session_id = nil if cookie_session_id == ''

# @current: create tomcalendar unless already created

print "Content-type: application/json\n\n#{result.to_json}"
