#! /usr/bin/ruby


cookie_session_id = ENV['HTTP_COOKIE']&.split(';')&.find{ |cookie| cookie.match?('session_id') }&.sub('session_id=','')&.strip
cookie_session_id = nil if cookie_session_id == ''

unless cookie_session_id
  puts "Content-type: text/html\n\n"
  puts %(
  <html lang="en">
    <body onload="reSignIn()"></body>
    <script>
      function reSignIn() {
        document.cookie = "session_id=;secure";
        window.location = "https://tomcalendar.com/";
      }
    </script>
  </html>
  )
  return
end


# @remember: handle refresh_tokens_and_cookie_session_id_is_valid?(cookie_session_id) during initial load and redirect to login if failed (delete cookie first)
# render dashboard
puts "Content-type: text/html\n\n"
puts %(
<html lang="en">
  <title>Dashboard</title>
  <head>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
  </head>
  <div class="navbar">
    <div class="nav search_bar">
      <i class="material-icons md-18 search" id="search">search</i>
      <input type="text" id="search_bar_input" placeholder="Search TomCalendar"></input>
    </div>
    <i class="material-icons md-36 nav create" id="create" onmousedown="onCreate()">create</i>
    <i class="material-icons md-36 nav select" id="user_settings" onmousedown="onUserSettings()">person</i>
    <i class="material-icons md-36 nav select" id="view_list" onmousedown="onViewList()">view_list</i>
    <i class="material-icons md-36 nav select" id="explore" onmousedown="onExplore()">explore</i>
  </div>
  <body onload="onExplore(); init();">
    <div class="settings_page", id="settings_page">
      <i class="material-icons md-48 settings">settings</i>
      <button class="settings_btn sign_out" onclick="signOut()">Sign out</button>
      <button class="settings_btn deactivate" onclick="confirmRevoke()">Deactivate</button>
    </div>
  </body>
  <script>
    function init() {
      gapi.load('auth2', function() {
        auth2 = gapi.auth2.init({
          client_id: '#{ENV['GOOGLE_OAUTH_CLIENT_ID']}',
          scope: 'profile email https://www.googleapis.com/auth/calendar',
          redirect_uri: 'postmessage'
        }).then(function(then_init) {}, function(error) {});
      });
    }
    function signOut() {
      document.cookie = "session_id=;secure";
      var auth2 = gapi.auth2.getAuthInstance();
      auth2.signOut();
      window.location = "https://tomcalendar.com/";
    }
    function confirmRevoke() {
			if (window.confirm("Deactivating your account will delete all your TomCalendar events from your google calendar. Are you sure you want to deactivate your account?")) {
				revoke();
			}
    }
    function revoke() {
      document.cookie = "session_id=;secure";
      var auth2 = gapi.auth2.getAuthInstance();
      auth2.disconnect();
      window.location = "https://tomcalendar.com/";
    }
    function onExplore() {
      unactivateAllNavIcons();
      unactivateAllPages();
      var explore_icon = document.getElementById("explore");
      explore_icon.style.color = "rgba(255, 255, 255, 1)";
      explore_icon.style.textShadow = "2px 2px 1px #000000";
      var search_bar = document.getElementById("search_bar_input");
      search_bar.placeholder = "Search TomCalendar";
    }
    function onUserSettings() {
      unactivateAllNavIcons();
      unactivateAllPages();
      var user_settings_icon = document.getElementById("user_settings");
      user_settings.style.color = "rgba(255, 255, 255, 1)";
      user_settings.style.textShadow = "2px 2px 1px #000000";

      var search_bar = document.getElementById("search_bar_input");
      search_bar.placeholder = "Search User Settings";

      var settings_page = document.getElementById("settings_page");
      settings_page.style.display = "block";
    }
    function onViewList() {
      unactivateAllNavIcons();
      unactivateAllPages();
      var explore_icon = document.getElementById("view_list");
      explore_icon.style.color = "rgba(255, 255, 255, 1)";
      explore_icon.style.textShadow = "2px 2px 1px #000000";
      var search_bar = document.getElementById("search_bar_input");
      search_bar.placeholder = "Search Event List";
    }
    function onCreate() {
    }
    function unactivateAllNavIcons() {
      var all_nav_icons = document.getElementsByClassName("material-icons nav select");
      for(var i = 0; i < all_nav_icons.length; i++){
        all_nav_icons[i].style.color = "rgba(255, 255, 255, .7)";
        all_nav_icons[i].style.textShadow = "1px 1px 1px #000000";
      }
    }
    function unactivateAllPages() {
      var settings_page = document.getElementById("settings_page");
      settings_page.style.display = "none";
    }
  </script>
  <style>
    html {
      text-align: center;
      background-color: #DB4437;
      font-family: 'Roboto', sans-serif;
    }
    .navbar {
      margin: 0;
      background-color: rgba(219, 68, 55, .7);
      width: 100%;
      overflow: auto;
      border-bottom-style: solid;
      border-width: thin;
      border-color: rgb(240, 240, 240, .25);
      padding-bottom: 6px;
      position: fixed;
    }
    .settings_page {
      display: none;
      position: absolute;
      width: 40%;
      top: 100px;
      text-align: center;
      margin-left: 30%;
      padding-bottom: 100px;
      border: solid;
      border-radius: 25px;
      border-width: 1px;
      border-color: #ECEFF1;
      background-color: #263238;
    }
    .material-icons {
      cursor: default;
    }
    .material-icons.settings {
      font-size: 64px;
      margin-top: 18px;
      width: 100%;
      color: #90A4AE;
    }
    .material-icons.nav {
      font-size: 36px;
      color: rgba(255, 255, 255, 1);
      float: right;
      text-align: center;
      margin-top: 6px;
      margin-left: 12px;
      margin-right: 12px;
      margin-bottom: 1px;
      text-shadow: 1px 1px 1px #000000;
      transition: color .175s, text-shadow .175s, background-color .175s;
      transition-timing-function: ease-out;
    }
    .material-icons.nav.select {
      color: rgba(255, 255, 255, .7);
      cursor: pointer;
    }
    .material-icons.nav.create {
      padding-top: 2px;
      color: #43A047;
      border-style: solid;
      border-color: rgb(66, 133, 244, 1);
      border-width: 2px;
      border-radius: 4px;
      background-color: #DB4437;
      margin-right: 64px;
      padding-left: 8px;
      padding-right: 8px;
      margin-top: 2px;
      padding-bottom: 3px;
      cursor: pointer;
    }
    .material-icons.search {
      float: left;
      margin-top: 4px;
      margin-left: 8px;
      margin-right: 2px;
    }
    .nav.search_bar {
      border: solid;
      border-radius: 25px;
      border-width: 1px;
      border-color: #ECEFF1;
      width: 512;
      height: 32;
      margin-top: 8px;
      margin-left: 64px;
      float: left;
      background-color: #DB4437;
      transition: box-shadow .175s, height .175s, width .175s;
      transition-timing-function: ease-out;
    }
    .nav.search_bar:hover {
      box-shadow: 0px 0px 4px black;
      border: none;
      width: 514;
      height: 33;
    }
    .nav.search_bar:focus-within {
      box-shadow: 0px 0px 4px black;
      border: none;
      width: 514;
      height: 33;
    }
    .nav.search_bar input[type=text] {
      float: left;
      padding: 12px;
      border: none;
      color: black;
      width: 470;
      height: 20px;
      margin-top: 4px;
      font-size: 16px;
      background-color: #DB4437;
    }
    .navbar input[type=text]:focus {
      border-color: #DB4437;
      outline: none;
    }
    .navbar input::placeholder {
      color: black;
      opacity: .75;
    }
    .settings_btn {
      display: inline-block;
      width: 50%;
      height: 64px;
      margin-top: 32px;
      font-size: 24px;
      outline: none;
      border: none;
      border-radius: 40px;
      cursor: pointer;
      box-shadow: 0px 0px 5px black;
      background-color: #455A64;
      transition: background-color .175s;
      transition-timing-function: ease-out;
      color: #ECEFF1;
    }
    .settings_btn:hover {
      background-color: #37474F;
    }
  </style>
</html>
)
