#! /usr/bin/ruby

# @optimize: requiring library is taking pretty long
require_relative '../lib/tom_calendar.rb'


cookie_session_id = get_session_id_from_cookies()
unless cookie_session_id && refresh_tokens_and_cookie_session_id_is_valid?(cookie_session_id)
  puts "Content-type: text/html\n\n"
  puts %(
  <html lang="en">
    <body onload="reSignIn()"></body>
    <script>
      function reSignIn() {
        document.cookie = "session_id=;secure";
        window.location = "https://tomcalendar.com/";
      }
    </script>
  </html>
  )
  return
end


# render dashboard
puts "Content-type: text/html\n\n"
puts %(
<html lang="en">
  <head>
    <script src="https://apis.google.com/js/platform.js?onload=init" async defer></script>
    <meta name="google-signin-client_id" content="#{ENV['GOOGLE_OAUTH_CLIENT_ID']}">
  </head>
  <h1>the dashboard</h1>
  <body>
    <a href="https://tomcalendar.com" onclick="signOut()">Sign out</a>
    <a href="https://tomcalendar.com/user_settings">Settings</a>
  </body>
  <script>
    function init() {
      gapi.load('auth2', function() {
        auth2 = gapi.auth2.init({
          client_id: '#{ENV['GOOGLE_OAUTH_CLIENT_ID']}',
          scope: 'profile email https://www.googleapis.com/auth/calendar',
          redirect_uri: 'postmessage'
        }).then(function(then_init) {}, function(error) {});
      });
    }
    function signOut() {
      document.cookie = "session_id=;secure";
      var auth2 = gapi.auth2.getAuthInstance();
      auth2.signOut();
    }
  </script>
</html>
)
