#! /usr/bin/ruby


cookie_session_id = ENV['HTTP_COOKIE']&.split(';')&.find{ |cookie| cookie.match?('session_id') }&.sub('session_id=','')&.strip
cookie_session_id = nil if cookie_session_id == ''

unless cookie_session_id
  puts "Content-type: text/html\n\n"
  puts %(
  <html lang="en">
    <body onload="reSignIn()"></body>
    <script>
      function reSignIn() {
        document.cookie = "session_id=;secure";
        window.location = "https://tomcalendar.com/";
      }
    </script>
  </html>
  )
  return
end

# render user settings
puts "Content-type: text/html\n\n"
puts %(
<html lang="en">
  <head>
    <script src="https://apis.google.com/js/platform.js?onload=init" async defer></script>
  </head>
  <h1>user settings</h1>
  <body>
    <a href="https://tomcalendar.com" onclick="revoke()">unauthorize</a>
  </body>
  <script>
    function init() {
      gapi.load('auth2', function() {
        auth2 = gapi.auth2.init({
          client_id: '#{ENV['GOOGLE_OAUTH_CLIENT_ID']}',
          scope: 'profile email https://www.googleapis.com/auth/calendar',
          redirect_uri: 'postmessage'
        }).then(function(then_init) {}, function(error) {});
      });
    }
    function revoke() {
      document.cookie = "session_id=;secure";
      var auth2 = gapi.auth2.getAuthInstance();
      auth2.disconnect();
    }
  </script>
<style>
  html {
    text-align: center;
    background-color: #DB4437;
  }
</stlye>
</html>
)
