#! /usr/bin/ruby

#raise ENV['HTTP_COOKIE']
cookie_session_id = ENV['HTTP_COOKIE']&.split(';')&.find{ |cookie| cookie.match?('session_id') }&.sub('session_id=','')&.strip
cookie_session_id = nil if cookie_session_id == ''

unless cookie_session_id
  print %(Content-type: text/html


  <html lang="en">
    <body onload="reSignIn()"></body>
    <script>
      function reSignIn() {
        window.location = "https://tomcalendar.com";
      }
    </script>
  </html>
  )
end

user_agent_str = ENV['HTTP_USER_AGENT']&.downcase.freeze || ''.freeze
IS_DESKTOP = !( /phone|android/.match(user_agent_str) )

html_file = IS_DESKTOP ? '/var/www/cgi-bin/tom_calendar/lib/generated_desktop_dashboard.html'.freeze : '/var/www/cgi-bin/tom_calendar/lib/generated_mobile_dashboard.html'.freeze

print File.read(html_file)
