#! /usr/bin/ruby

# @remember: need more scalable border widths?
# @remember: should make datepicker tooltip pretty
# @remember: should download the jquery libs locally (maybe concatenate?)
# @remember: decide if delete session item on logout or periodically delete "expired" sessions
# @remember: change UI scale if desktop
# @remember: use vh for font heights? (I've only been using vw's for font sizes)
# @remember: fix flicker/ double tap bug by choosing omnousedon or ontouchstart
# @test:     sign out on mobile and confirm google api not deactivated
# @test:     user agent detection on several platforms

# @current: rewrite signing out and deactivating


cookie_session_id = ENV['HTTP_COOKIE']&.split(';')&.find{ |cookie| cookie.match?('session_id') }&.sub('session_id=','')&.strip
cookie_session_id = nil if cookie_session_id == ''

unless cookie_session_id
  print "Content-type: text/html\n\n"
  print %(
  <html lang="en">
    <body onload="reSignIn()"></body>
    <script>
      function reSignIn() {
        window.location = "https://tomcalendar.com";
      }
    </script>
  </html>
  )
  return
end

user_agent_str = ENV['HTTP_USER_AGENT'].downcase
IS_DESKTOP = !( /phone|android/.match(user_agent_str) )
VW_FACTOR  = IS_DESKTOP ? 0.35 : 1
VH_FACTOR  = IS_DESKTOP ? 0.93 : 1


# render dashboard
print "Content-type: text/html\n\n"
print %(
<html lang="en">
  <title>Dashboard</title>
  <head>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Outlined" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
  </head>
  <div id="background">
    <div id="navbar">
      <i class="material-icons-outlined md-36 nav select" id="explore" onmousedown="onNavIconSelect('explore')" ontouchstart="onNavIconSelect('explore')">explore</i>
      <div class="navbar_space"></div>
      <i class="material-icons-outlined md-36 nav select" id="search" ontouchstart="onNavIconSelect('search')" onmousedown="onNavIconSelect('search')">search</i>
      <i class="material-icons-outlined md-36 nav create" id="create" ontouchstart="onCreate()" onmousedown="onCreate()">create</i>
      <i class="material-icons-outlined md-36 nav select" id="profile" ontouchstart="onNavIconSelect('profile')" onmousedown="onNavIconSelect('profile')">person</i>
      <div class="navbar_space"></div>
      <i class="material-icons-outlined md-36 nav select" id="settings" ontouchstart="onNavIconSelect('settings');" onmousedown="onNavIconSelect('settings')">settings</i>
    </div>
    <body onload="onNavIconSelect('explore'); init();">
      <div class="page", id="explore_page">
        <h1>explore</h1>
      </div>
      <div class="page", id="search_page">
        <h1>search</h1>
      </div>
      <div class="page", id="profile_page">
        <h1>profile</h1>
      </div>
      <div class="page", id="settings_page">
        <h1 style="text-align:left;font-size:#{8 * VW_FACTOR}vw;margin-left:#{4 * VW_FACTOR}vw;margin-top:#{10 * VW_FACTOR}vw">Settings</h1>
        <button class="settings_btn" onclick="onViewSessions()">Sessions</button>
        <button class="settings_btn" onclick="confirmRevoke()">Deactivate</button>
        <button class="settings_btn" id="log_out_btn" onclick="signOut()">Log out</button>
        <div class="page_anchor_hack"></div>
      </div>
    </body>
  </div>
  <div class="create_form_close_layer" id="create_form_close_layer" onmousedown="onCreateClose()"></div>
  <div class="create_form" id="create_form">
    <i class="material-icons md-48 create_close" id="create_close" onmousedown="onCreateClose()">close</i>
    <div class="event_form_title"><input type="text" id="event_title_input" placeholder="Add title"></input></div>
    <div class="event_datetime">
      <div class="start_date"><input type="text" id="datepicker" placeholder="Add date"></div>
      <div class="start_time">
        <input type="text" id="start_time" placeholder="Add time" onmousedown="showTimepicker('start_timepicker')">
        <div class="timepicker" id="start_timepicker">
          <select size="5" id="start_time_selectbox" onChange="onStartTimepickerChange(this)" onblur="closeTimepicker('start_timepicker')">
            <option value="12:00am" class="timepicker-options">12:00am</option>
            <option value="12:15am" class="timepicker-options">12:15am</option>
            <option value="12:30am" class="timepicker-options">12:30am</option>
            <option value="12:45am" class="timepicker-options">12:45am</option>
            <option value="1:00am" class="timepicker-options">1:00am</option>
            <option value="1:15am" class="timepicker-options">1:15am</option>
            <option value="1:30am" class="timepicker-options">1:30am</option>
            <option value="1:45am" class="timepicker-options">1:45am</option>
            <option value="2:00am" class="timepicker-options">2:00am</option>
            <option value="2:15am" class="timepicker-options">2:15am</option>
            <option value="2:30am" class="timepicker-options">2:30am</option>
            <option value="2:45am" class="timepicker-options">2:45am</option>
            <option value="3:00am" class="timepicker-options">3:00am</option>
            <option value="3:15am" class="timepicker-options">3:15am</option>
            <option value="3:30am" class="timepicker-options">3:30am</option>
            <option value="3:45am" class="timepicker-options">3:45am</option>
            <option value="4:00am" class="timepicker-options">4:00am</option>
            <option value="4:15am" class="timepicker-options">4:15am</option>
            <option value="4:30am" class="timepicker-options">4:30am</option>
            <option value="4:45am" class="timepicker-options">4:45am</option>
            <option value="5:00am" class="timepicker-options">5:00am</option>
            <option value="5:15am" class="timepicker-options">5:15am</option>
            <option value="5:30am" class="timepicker-options">5:30am</option>
            <option value="5:45am" class="timepicker-options">5:45am</option>
            <option value="6:00am" class="timepicker-options">6:00am</option>
            <option value="6:15am" class="timepicker-options">6:15am</option>
            <option value="6:30am" class="timepicker-options">6:30am</option>
            <option value="6:45am" class="timepicker-options">6:45am</option>
            <option value="7:00am" class="timepicker-options">7:00am</option>
            <option value="7:15am" class="timepicker-options">7:15am</option>
            <option value="7:30am" class="timepicker-options">7:30am</option>
            <option value="7:45am" class="timepicker-options">7:45am</option>
            <option value="8:00am" class="timepicker-options">8:00am</option>
            <option value="8:15am" class="timepicker-options">8:15am</option>
            <option value="8:30am" class="timepicker-options">8:30am</option>
            <option value="8:45am" class="timepicker-options">8:45am</option>
            <option value="9:00am" class="timepicker-options">9:00am</option>
            <option value="9:15am" class="timepicker-options">9:15am</option>
            <option value="9:30am" class="timepicker-options">9:30am</option>
            <option value="9:45am" class="timepicker-options">9:45am</option>
            <option value="10:00am" class="timepicker-options">10:00am</option>
            <option value="10:15am" class="timepicker-options">10:15am</option>
            <option value="10:30am" class="timepicker-options">10:30am</option>
            <option value="10:45am" class="timepicker-options">10:45am</option>
            <option value="11:00am" class="timepicker-options">11:00am</option>
            <option value="11:15am" class="timepicker-options">11:15am</option>
            <option value="11:30am" class="timepicker-options">11:30am</option>
            <option value="11:45am" class="timepicker-options">11:45am</option>
            <option value="12:00pm" class="timepicker-options">12:00pm</option>
            <option value="12:15pm" class="timepicker-options">12:15pm</option>
            <option value="12:30pm" class="timepicker-options">12:30pm</option>
            <option value="12:45pm" class="timepicker-options">12:45pm</option>
            <option value="1:00pm" class="timepicker-options">1:00pm</option>
            <option value="1:15pm" class="timepicker-options">1:15pm</option>
            <option value="1:30pm" class="timepicker-options">1:30pm</option>
            <option value="1:45pm" class="timepicker-options">1:45pm</option>
            <option value="2:00pm" class="timepicker-options">2:00pm</option>
            <option value="2:15pm" class="timepicker-options">2:15pm</option>
            <option value="2:30pm" class="timepicker-options">2:30pm</option>
            <option value="2:45pm" class="timepicker-options">2:45pm</option>
            <option value="3:00pm" class="timepicker-options">3:00pm</option>
            <option value="3:15pm" class="timepicker-options">3:15pm</option>
            <option value="3:30am" class="timepicker-options">3:30am</option>
            <option value="3:45pm" class="timepicker-options">3:45pm</option>
            <option value="4:00pm" class="timepicker-options">4:00pm</option>
            <option value="4:15pm" class="timepicker-options">4:15pm</option>
            <option value="4:30pm" class="timepicker-options">4:30pm</option>
            <option value="4:45pm" class="timepicker-options">4:45pm</option>
            <option value="5:00pm" class="timepicker-options">5:00pm</option>
            <option value="5:15pm" class="timepicker-options">5:15pm</option>
            <option value="5:30pm" class="timepicker-options">5:30pm</option>
            <option value="5:45pm" class="timepicker-options">5:45pm</option>
            <option value="6:00pm" class="timepicker-options">6:00pm</option>
            <option value="6:15pm" class="timepicker-options">6:15pm</option>
            <option value="6:30pm" class="timepicker-options">6:30pm</option>
            <option value="6:45pm" class="timepicker-options">6:45pm</option>
            <option value="7:00pm" class="timepicker-options">7:00pm</option>
            <option value="7:15pm" class="timepicker-options">7:15pm</option>
            <option value="7:30pm" class="timepicker-options">7:30pm</option>
            <option value="7:45pm" class="timepicker-options">7:45pm</option>
            <option value="8:00pm" class="timepicker-options">8:00pm</option>
            <option value="8:15pm" class="timepicker-options">8:15pm</option>
            <option value="8:30pm" class="timepicker-options">8:30pm</option>
            <option value="8:45pm" class="timepicker-options">8:45pm</option>
            <option value="9:00pm" class="timepicker-options">9:00pm</option>
            <option value="9:15pm" class="timepicker-options">9:15pm</option>
            <option value="9:30pm" class="timepicker-options">9:30pm</option>
            <option value="9:45pm" class="timepicker-options">9:45pm</option>
            <option value="10:00pm" class="timepicker-options">10:00pm</option>
            <option value="10:15pm" class="timepicker-options">10:15pm</option>
            <option value="10:30pm" class="timepicker-options">10:30pm</option>
            <option value="10:45pm" class="timepicker-options">10:45pm</option>
            <option value="11:00pm" class="timepicker-options">11:00pm</option>
            <option value="11:15pm" class="timepicker-options">11:15pm</option>
            <option value="11:30pm" class="timepicker-options">11:30pm</option>
            <option value="11:45pm" class="timepicker-options">11:45pm</option>
          </select>
        </div>
      </div>
      <div class="event_datetime_text">to</div>
      <div class="end_time">
        <input type="text" id="end_time" placeholder="Add time"></input>
      </div>
    </div>
  </div>
  <script>
    function init() {
      $.ajax({
        type: 'POST',
        url: 'https://tomcalendar.com/validate_tokens_and_load_initial_content',
        contentType: 'application/octet-stream; charset=utf-8',
        success: function(result) {
          if (result["is_valid"]) {
            // handle initial data load

            $.ajax({
              type: 'POST',
              url: 'https://tomcalendar.com/create_tomcalendar_if_needed',
              contentType: 'application/octet-stream; charset=utf-8',
              processData: false,
              data: ''
            });

            // @remember: should probably post request to fix potential out of sync event changes (should make sure occurs after calendar is created)
          } else {
            document.cookie = "session_id=;secure";
            window.location = "https://tomcalendar.com/";
          }
        },
        processData: false,
        data: ''
      });

      gapi.load('auth2', function() {
        auth2 = gapi.auth2.init({
          client_id: '#{ENV['GOOGLE_OAUTH_CLIENT_ID']}',
          scope: 'profile email https://www.googleapis.com/auth/calendar',
          redirect_uri: 'postmessage'
        }).then(function(then_init) {}, function(error) {});
      });

      // @remember: this is a fix for blur moving around stuff when blurred then not moving them back, so things should be slighlty moved by default
      document.getElementById("background").style.webkitFilter = "blur(4px)";
      document.getElementById("background").style.webkitFilter = "blur(0px)";
    }
    function signOut() {
      document.cookie = "session_id=;secure";
      var auth2 = gapi.auth2.getAuthInstance();
      auth2.signOut();
      window.location = "https://tomcalendar.com/";
    }
    function confirmRevoke() {
      if (window.confirm("Deactivating your account will delete all your TomCalendar events from your google calendar. Are you sure you want to deactivate your account?")) {
        revoke();
      }
    }
    function revoke() {
      $.ajax({
        type: 'POST',
        url: 'https://tomcalendar.com/delete_tomcalendar',
        contentType: 'application/octet-stream; charset=utf-8',
        processData: false,
        data: ''
      });
      document.cookie = "session_id=;secure";
      var auth2 = gapi.auth2.getAuthInstance();
      auth2.disconnect();
      window.location = "https://tomcalendar.com/";
    }
    function onNavIconSelect(nav_icon_id) {
      unactivateAllNavIcons();
      unactivateAllPages();
      var nav_icon = document.getElementById(nav_icon_id);
      nav_icon.style.color = "black";
      nav_icon.className = "material-icons nav select";

      var page = document.getElementById(nav_icon_id + "_page");
      page.style.display = "block";
    }
    function onCreate() {
      document.getElementById("background").style.webkitFilter = "blur(4px)";
      var create_form = document.getElementById("create_form");
      var create_form_close_layer = document.getElementById("create_form_close_layer");
      create_form_close_layer.style.display = "block";
      create_form.style.display = "block";
    }
    function onCreateClose() {
      document.getElementById("background").style.webkitFilter = "blur(0px)";
      var create_form = document.getElementById("create_form");
      var create_form_close_layer = document.getElementById("create_form_close_layer");
      create_form_close_layer.style.display = "none";
      create_form.style.display = "none";
    }
    function unactivateAllNavIcons() {
      var all_nav_icons = document.getElementsByClassName("material-icons nav select");
      for(var i = 0; i < all_nav_icons.length; i++){
        //all_nav_icons[i].style.color = "rgba(0, 0, 0, .7)";
        all_nav_icons[i].className = "material-icons-outlined nav select";
      }
    }
    function unactivateAllPages() {
      var all_pages = document.getElementsByClassName("page");
      for(var i = 0; i < all_pages.length; i++){
        all_pages[i].style.display = "none";
      }
    }
    $("#datepicker").datepicker({
      dateFormat: "M d, yy",
      dayNamesMin: [ "S","M","T","W","T","F","S" ],
      duration: 0,
      showOtherMonths: true,
      beforeShow: function(input_element, obj) {
        input_element.setSelectionRange(0,input_element.value.length);
      }
    });
    function showTimepicker(timepicker_id) {
      var timepicker = document.getElementById(timepicker_id);
      timepicker.style.display = "block";
    }
    function closeTimepicker(timepicker_id) {
      var timepicker = document.getElementById(timepicker_id);
      timepicker.style.display = "none";
    }
    function onStartTimepickerChange(obj) {
      document.getElementById("start_time").value = obj.value;
      closeTimepicker("start_timepicker");
    }
  </script>
  <style>
    html {
      text-align: center;
      background-color: #FEFFFE;
      border: none;
      font-family: 'Roboto', sans-serif;
    }
    #navbar {
      margin: 0;
      background-color: rgba(254, 255, 254, .7);
      width: 100%;
      overflow: auto;
      border-bottom-style: solid;
      border-width: thin;
      border-color: rgba(235, 239, 240, 1);
      position: fixed;
    }
    #background {
      transition: all .175s;
      border: none;
    }
    .create_form {
      display: none;
      position: fixed;
      width: 70%;
      margin-top: 100px;
      text-align: center;
      margin-left: 15%;
      padding-bottom: 100px;
      border: solid;
      border-radius: 25px;
      border-width: 1px;
      border-color: white;
      background-color: white;

      height: 50%; // testinggg
    }
    .create_form_close_layer {
      display: none;
      width: 100%;
      height: 100%;
      position: fixed;
    }
    .page {
      display: none;
      position: absolute;
      border: none;
      width: 100%;
      margin-top: #{12 * VW_FACTOR}vw;
    }
    .material-icons, .material-icons-outlined {
      cursor: default;
    }
    .material-icons.nav, .material-icons-outlined.nav {
      margin-top: #{2 * VW_FACTOR}vw;
      margin-bottom: #{2 * VW_FACTOR}vw;
      font-size: #{7 * VW_FACTOR}vw;
      //color: rgba(255, 255, 255, 1);
      color: #000000;
      text-align: center;
      transition: color .175s;
      transition-timing-function: ease-out;
    }
    .material-icons.nav.select, .material-icons-outlined.nav.select {
      //color: rgba(255, 255, 255, .7);
      color: #000000;
      cursor: pointer;
    }
    .material-icons.nav.create, .material-icons-outlined.nav.create {
      color: #0F9D58;
      border-style: solid;
      border-color: #4285F4;
      border-width: medium;
      border-radius: 8%; 
      padding-right:  #{3 * VW_FACTOR}vw;
      margin-right:   #{9 * VW_FACTOR}vw;
      padding-left:   #{3 * VW_FACTOR}vw;
      margin-left:    #{9 * VW_FACTOR}vw;
      cursor: pointer;
      transition: background-color .175s;
      transition-timing-function: ease-out;
    }
    .material-icons.create_close {
      float: right;
      margin-right: 16px;
      margin-top: 16px;
      cursor: pointer;
      border-radius: 50px;
      font-size: 40px;
      color: #616161;
      padding: 4px;
    }
    .material-icons.create_close:hover {
      background-color: #EEEEEE;
    }
    .material-icons.nav.create:hover {
      background-color: #d9392b;
    }
    .material-icons.search, .material-icons-outlined.search {
      float: left;
      margin-top: 4px;
      margin-left: 8px;
      margin-right: 2px;
    }
    .search_bar {
      border: solid;
      border-radius: 25px;
      border-width: 1.5px;
      border-color: black;
      width: 512;
      height: 32;
      margin-top: 8px;
      margin-left: 64px;
      float: left;
      transition: box-shadow .175s, height .175s, width .175s;
      transition-timing-function: ease-out;
    }
    .search_bar:hover {
      box-shadow: 0px 0px 4px black;
      border: none;
      width: 514;
      height: 33;
    }
    .search_bar:focus-within {
      box-shadow: 0px 0px 4px black;
      border: none;
      width: 514;
      height: 33;
    }
    .search_bar input[type=text] {
      float: left;
      padding: 12px;
      border: none;
      color: black;
      width: 470;
      height: 20px;
      margin-top: 4px;
      font-size: 16px;
    }
    #navbar input[type=text]:focus {
      outline: none;
    }
    #navbar input::placeholder {
      color: black;
      opacity: .75;
    }
    .settings_btn {
      display: inline-block;
      width: 100%;
      height: #{6 * VH_FACTOR}vh;
      font-size: 32px;
      outline: none;
      text-align: left;

      border-top-style: hidden;
      border-right-style: hidden;
      border-left-style: hidden;
      border-bottom-style: solid;
      border-bottom-width: thin;
      border-bottom-color: #90CAF9;
      border-radius: 0;
 
      cursor: pointer;
      //box-shadow: 0px 0px 5px black;
      background-color: rgba(254, 255, 254, 1);
      transition: background-color .175s;
      transition-timing-function: ease-out;
      color: black;
    }
    .settings_btn:hover {
      //background-color: #37474F;
    }
    #log_out_btn {
      text-align: center;
    }
    .page_anchor_hack {
      margin-top: #{56 * VH_FACTOR}vh;
    }
    .event_form_title input[type=text] {
      float: left;
      border-top-style: hidden;
      border-right-style: hidden;
      border-left-style: hidden;
      border-bottom-style: solid;
      border-bottom-width: thin;
      border-bottom-color: #90CAF9;
      border-radius: 0;
      width: 60%;
      height: 64px;
      font-size: 40px;
      margin-top: 14px;
      margin-left: 16px;
      color: #424242;
      background-color: white;
    }
    .event_form_title input[type=text]:focus {
      border-color: #2962FF;
      outline: none;
      border-width: 2px;
    }
    .event_form_title input::placeholder {
      color: #757575;
    }
    .create_form_space {
      width: 60%;
      display: inline-block;
    }
    .event_datetime {
      margin: 0;
      padding: 0;
      width: 60%;
    }
    .start_date {
      display: inline-block;
      float: left;
      margin-top: 24px;
      margin-right: 16px;
    }
    .event_datetime_text {
      display: inline-block;
      float: left;
      margin-top: 36px;
      margin-left: 8px;
      margin-right: 8px;
      text-align: center;
      font-size: 15;
      color: #424242;
    }
    .start_date input[type=text] {
      border-width: .5px;
      border-bottom-width: 2px;
      border-color: #EEEEEE;
      border-radius: 3px;
      border-style: solid;
      margin-left: 16px;
      width: 128px;
      height: 42px;
      background-color: #EEEEEE;
      color: #424242;
      font-size: 18;
      float: left;
      text-align: center;
    }
    .start_date input::placeholder {
      color: #757575;
    }
    .start_date input[type=text]:focus {
      outline: none;
      border-bottom-color: #2962FF;
    }
    .start_time, .end_time {
      display: inline-block;
      float: left;
      margin-top: 24px;
      margin-left: 0;
      margin-right: 0;
    }
    .start_time input[type=text], .end_time input[type=text] {
      border-width: .5px;
      border-bottom-width: 2px;
      border-color: #EEEEEE;
      border-radius: 3px;
      border-style: solid;
      width: 98px;
      height: 42px;
      background-color: #EEEEEE;
      color: #424242;
      font-size: 18;
      float: left;
      text-align: center;
    }
    .start_time input[type=text]:focus, .end_time input[type=text]:focus {
      outline: none;
      border-bottom-color: #2962FF;
    }
    .ui-datepicker {
      background-color: white;
      margin-top: 8px;
      box-shadow: 0px 4px 8px 0px rgba(0, 0, 0, .4);
      border-radius: 2px;
      width: 330px;
    }
    .ui-datepicker a {
      text-decoration: none;
    }
    .ui-datepicker table {
      width: 88%;
      height: 200px;
      margin-left: 6%;
      margin-right: 6%;
      margin-bottom: 6%;
      text-align: center;
    }
    .ui-datepicker-header {
      margin-top: 2%;
      margin-bottom: 8px;
      text-align: right;
    }
    .ui-datepicker-title {
      float: left;
      margin-left: 9.5%;
      margin-top: 1.4%;
      color: #424242;
      cursor: default;
    }
    .ui-datepicker-prev, .ui-datepicker-next {
      display: inline-block;
      cursor: pointer;
      color: transparent;
      border-color: black;
      width: 26px;
      height: 26px;
      font-size: 0px;
      border-radius: 50px;
    }
    .ui-datepicker-prev:hover, .ui-datepicker-next:hover {
      background-color: #EEEEEE;
      text-decoration: none;
    }
    .ui-datepicker-prev {
      background-image: url('https://tomcalendar.com/public/prev_arrow.png');
      background-repeat: no-repeat;
      background-size: 92%;
      margin-right: 1.25%;
      background-position: left 1px;
    }
    .ui-datepicker-next {
      background-image: url('https://tomcalendar.com/public/next_arrow.png');
      background-repeat: no-repeat;
      background-size: 92%;
      margin-right: 7.5%;
      background-position: right 1px;
    }
    .ui-datepicker th {
      font-size: 14px;
      color: #9E9E9E;
      font-weight: normal;
      cursor: default;
      padding-bottom: 8px;
    }
    .ui-datepicker td span, .ui-datepicker td a {
      display: inline-block;
      width: 28px;
      height: 28px;
      line-height: 28px;
      text-align: center;
      border-radius: 50px;
      font-size: 14px;
      color: #616161;
    }
    .ui-datepicker-unselectable .ui-state-default {
      color: #9E9E9E;
      cursor: default;
    }
    .ui-datepicker-calendar .ui-state-hover {
      background-color: #EEEEEE;
    }
    .ui-datepicker-calendar .ui-state-active {
      background-color: #BBDEFB;
      color: #2962FF;
    }
    .ui-datepicker-today .ui-state-default {
      color: white;
      background-color: #2962FF;
    }
    .timepicker {
      display: none;
      overflow-y: auto;
      position: absolute;
      margin-top: 50px;
      box-shadow: 0px 4px 8px 0px rgba(0, 0, 0, .4);
      border-radius: 2px;
    }
    .timepicker select {
      border-width: .5px;
      border-bottom-width: 2px;
      border-color: white;
      border-radius: 3px;
      border-style: solid;
      width: 220px;
      background-color: white;
      color: #424242;
      font-size: 18;
      text-align: left;
    }
    .timepicker select:focus {
      outline: none;
    }
    .timepicker-options {
      padding-left: 12px;
      padding-top: 12px;
      padding-bottom: 12px;
      color: #424242;
    }
    .timepicker-options:hover {
      background-color: #EEEEEE;
    }
    ::-webkit-scrollbar {
      width: 11px;
    }
    ::-webkit-scrollbar-thumb {
      border-radius: 25px;
      -webkit-border-radius: 25px;
      height: 50px;
      background: #BDBDBD;
    }
    ::-webkit-scrollbar-thumb:active {
      background: #9E9E9E;
    }
    .navbar_space {
      width: #{12 * VW_FACTOR}vw;
      display: inline-block;
    }
    #settings_page {
      background-color: #F2F2F7;
    }
  </style>
</html>
)
