#! /usr/bin/ruby

require_relative '../lib/tom_calendar.rb'
require "google/apis/calendar_v3"

cookie_session_id = ENV['HTTP_COOKIE']&.split(';')&.find{ |cookie| cookie.match?('session_id') }&.sub('session_id=','')&.strip
cookie_session_id = nil if cookie_session_id == ''

unless cookie_session_id
  print StatusCodeStr::BAD_REQUEST
  return
end

session_id            = JSON.parse(cookie_session_id)
dynamodb              = Aws::DynamoDB::Client.new(region: ENV['AWS_REGION'])
google_id             = session_id['google_id']
google_authorizer     = get_google_authorizer(dynamodb)
service               = Google::Apis::CalendarV3::CalendarService.new
service.authorization = google_authorizer.get_credentials(google_id)
service.client_options.application_name = 'TomCalendar'.freeze

google_authorizer.revoke_authorization(google_id)

# get google calendar id
begin
  params = {
    table_name: 'GoogleCalendarIDs',
    key: { google_id: google_id }
  }

  result_item = dynamodb.get_item(params)&.item || {}
  google_calendar_id = result_item['google_calendar_id']
rescue Exception => e
  print StatusCodeStr::error_message(e.message)
  return
end

# delete google calendar if exists
if google_calendar_id
  service.delete_calendar(google_calendar_id)

  params = {
    table_name: 'GoogleCalendarIDs',
    key: { google_id: google_id }
  }

  begin
    dynamodb.delete_item(params)
  rescue
    print StatusCodeStr::error_message('Unable to delete google calendar id')
    return
  end
end

print StatusCodeStr::OK
