#! /usr/bin/ruby

require_relative '../lib/tom_calendar.rb'

dynamodb          = Aws::DynamoDB::Client.new(region: ENV['AWS_REGION'])
google_authorizer = get_google_authorizer(dynamodb)
authorization_url = google_authorizer.get_authorization_url base_url: 'https://tomcalendar.com'

print StatusCodeStr::plain_text(authorization_url)
