#! /usr/bin/ruby

session_id = get_session_id_from_cookies()
current_google_id = session_id['google_id']

cache_result = `tom_memcache_get 'get_promoted_events'`.freeze
cache_result = nil if (cache_result == '')

if cache_result
  events = JSON.parse(cache_result)
  is_reminder_set_hash = generate_is_reminder_set_hash(current_google_id,events)
  events.each do |event|
    event['is_reminder_set'] = true if is_reminder_set_hash["#{event['google_id']}-#{event['title']}"]
  end
  return "Content-type: application/json\n\n#{events.to_json.freeze}"
end

dynamodb = Aws::DynamoDB::Client.new(region: TomEnv::get('AWS_REGION'))
promoted_event_ids = dynamodb.scan({ table_name: 'PromotedEventIDs' })&.items
unless promoted_event_ids
  return "Content-type: application/json\n\n#{[].to_json}"
end
promoted_event_ids.sort_by! { |promoted_event_key| promoted_event_key['id'].to_i }
promoted_event_keys = promoted_event_ids.map { |item| { google_id: item['google_id'], title: item['title'] } }

batch_events_result = dynamodb.batch_get_item({
  request_items: {
    "Events" => {
      keys: promoted_event_keys,
    },
  },
})

promoted_events = batch_events_result.responses["Events"]
result = []
promoted_event_ids.each do |promoted_event_id|
  promoted_events.each do |promoted_event|
    if (promoted_event_id['google_id'] == promoted_event['google_id']) && (promoted_event_id['title'] == promoted_event['title'])
      result.push(promoted_event)
      break
    end
  end
end

TomMemcache::set("get_promoted_events", result.to_json, 86400)  # 86400 seconds is 24 hours

is_reminder_set_hash = generate_is_reminder_set_hash(current_google_id,result)
result.each do |event|
  event['is_reminder_set'] = true if is_reminder_set_hash["#{event['google_id']}-#{event['title']}"]
end

result_to_json = result.to_json.freeze
return "Content-type: application/json\n\n#{result_to_json}"
