#! /usr/bin/ruby


cache_result = `tom_memcache_get 'get_promoted_events'`.freeze
cache_result = nil if (cache_result == '')

if cache_result
  print "Content-type: application/json\n\n#{cache_result}"
  return
end


require_relative '../lib/tom_calendar.rb'

=begin
cache_result = TomMemcache::get("get_promoted_events").freeze
=end

dynamodb = Aws::DynamoDB::Client.new(region: ENV['AWS_REGION'])
promoted_event_ids = dynamodb.scan({ table_name: 'PromotedEventIDs' })&.items
unless promoted_event_ids
  print "Content-type: application/json\n\n#{[].to_json}"
  return
end
promoted_event_ids.sort_by! { |promoted_event_key| promoted_event_key['id'] }
promoted_event_keys = promoted_event_ids.map { |item| { google_id: item['google_id'], title: item['title'] } }

batch_events_result = dynamodb.batch_get_item({
  request_items: {
    "Events" => {
      keys: promoted_event_keys,
    },
  },
})

promoted_events = batch_events_result.responses["Events"]
result = []
promoted_event_ids.each do |promoted_event_id|
  promoted_events.each do |promoted_event|
    if (promoted_event_id['google_id'] == promoted_event['google_id']) && (promoted_event_id['title'] == promoted_event['title'])
      result.push(promoted_event)
      break
    end
  end
end

result_to_json = result.to_json.freeze
TomMemcache::set("get_promoted_events", result_to_json, 86400)  # 86400 seconds is 24 hours
print "Content-type: application/json\n\n#{result_to_json}"
