#! /usr/bin/ruby

# @remember: mention users can forget about dates, timzones, etc... in description?
# @remember: remove login if already logged in


cookie_session_id = ENV['HTTP_COOKIE']&.split(';')&.find{ |cookie| cookie.match?('session_id') }&.sub('session_id=','')&.strip
cookie_session_id = nil if cookie_session_id == ''

user_agent_str = ENV['HTTP_USER_AGENT'].downcase
IS_DESKTOP = !( /phone|android/.match(user_agent_str) )
VW_FACTOR  = IS_DESKTOP ? 0.35 : 1


print "Content-type: text/html\n\n"
print %(
<html lang="en">
  <title>Login</title>
  <head>
    <link rel="preload" as="image" href="https://tomcalendar.com/public/favicon.ico">
    <link rel="preload" as="image" href="https://tomcalendar.com/public/google_signin_buttons/web/2x/btn_google_signin_dark_pressed_web@2x.png">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
  </head>
  <body onload="init();" id="background">
    <div class="firefox_hack"><img src="https://tomcalendar.com/public/google_signin_buttons/web/2x/btn_google_signin_dark_pressed_web@2x.png" alt="firefox_hack" style="display:none;"></div>
    <div id="description_and_button">
      <div id="description">
        <div id="description_content">
          <h1 style="font-size:2vw;">You've earned your audience's attention, keep it</h1>
          <ul class="description_list">
            <li><i class="material-icons">create</i> Create planned and spontaneous events</li>
            <li><i class="material-icons">update</i> Replicate event changes automatically</li>
            <li><i class="material-icons">analytics</i> Analyze interest for your events</li>
          </ul>
          <h1 style="font-size:2vw;">Stay in the know, without spam</h1>
          <ul class="description_list">
            <li><i class="material-icons">search</i> Find out when events happen</li>
            <li><i class="material-icons">sync</i> Sync events with Google Calendar</li>
            <li><i class="material-icons">explore</i> Explore trending events</li>
          </ul>
        </div>
      </div>
      <div id="google_button_wrapper">
        <button class="google_button" id="google_login" onmousedown="onSignUp()"></button>
      </div>
    </div>
  </body>
  <script>
    function init() {
      gapi.load('auth2', function() {
        auth2 = gapi.auth2.init({
          client_id: '#{ENV['GOOGLE_OAUTH_CLIENT_ID']}',
          scope: 'profile email https://www.googleapis.com/auth/calendar',
          redirect_uri: 'postmessage'
        }).then(function(then_init) {}, function(error) {});
      });
    }
    function onSignUp() {
      var auth2 = gapi.auth2.getAuthInstance();
      auth2.grantOfflineAccess().then(onSignIn);
    }
    function onSignIn(authResponse) {
      if (authResponse['code']) {
        var auth2 = gapi.auth2.getAuthInstance();

        $.ajax({
          type: 'POST',
          url: 'https://tomcalendar.com/authorize_gmail',
          contentType: 'application/octet-stream; charset=utf-8',
          success: function(result) {
            var today_time = new Date().getTime();
            var expiration_date = new Date();
            expiration_date.setTime(today_time + (1000 *31536000));
            document.cookie = "session_id=" + JSON.stringify(result) + ";expires=" + expiration_date.toGMTString() +";secure";
            window.location = "https://tomcalendar.com/dashboard";
          },
          error: function(result) {
            revoke();
          },
          processData: false,
          data: authResponse['code']
        });

        document.getElementById("background").style.webkitFilter = "blur(100px)";
      } else {
        // Didn't find code in authResponse
        revoke();
      }
    }
    function revoke() {
      var auth2 = gapi.auth2.getAuthInstance();
      auth2.disconnect();
      window.location = "https://tomcalendar.com";
    }
  </script>
  <style type="text/css">
    html {
      text-align: center;
      font-family: 'Roboto', sans-serif;
    }
    h1 {
      margin: 0;
    }
    body {
      transition: all 10s;
      transition-timing-function: ease-out;
    }
    .material-icons {
      font-size: 1.5vw;
    }
    ul.description_list {
      list-style-type: none;
      padding: 0;
      font-size: 1.5vw;
      margin-top: 8px;
    }
    #description_and_button {
      margin-top: 12%;
      margin-left: 12%;
      width: 88%;
    }
    #description {
      width: 50%;
      height: 50%;
      text-align: left;
      display: inline-block;
      float: left;
    }
    #description_content {
      float: right;
    }
    #google_button_wrapper {
      width: 48%;
      height: 50%;
      display: inline-block;
      text-align: left;
      margin-top: 10%;
    }
    .google_button {
      width: 250px;
      height: 60px;
      border: none;
      background: url('https://tomcalendar.com/public/google_signin_buttons/web/2x/btn_google_signin_dark_normal_web@2x.png') no-repeat;
      background-size: cover;
      border-radius: 3px;
      cursor: pointer;
      transition: background .175s;
      transition-timing-function: ease-out;
    }
    .google_button:hover {
      background: url('https://tomcalendar.com/public/google_signin_buttons/web/2x/btn_google_signin_dark_pressed_web@2x.png') no-repeat;
      background-size: cover;
    }
    .google_button:active {
      background: url('https://tomcalendar.com/public/google_signin_buttons/web/2x/btn_google_signin_dark_pressed_web@2x.png') no-repeat;
      background-size: cover;
    }
  </style>
</html>
)
