#! /usr/bin/ruby

cookie_session_id = ENV['HTTP_COOKIE']&.split(';')&.find{ |cookie| cookie.match?('session_id') }&.sub('session_id=','')&.strip
cookie_session_id = nil if cookie_session_id == ''

unless cookie_session_id
  print StatusCodeStr::BAD_REQUEST
  return
end

cache_result = `tom_memcache_get 'load_sessions#{cookie_session_id}'`.freeze
cache_result = nil if (cache_result == '')

if cache_result
  print "Content-type: application/json\n\n#{cache_result}"
  return
end


require_relative '../lib/tom_calendar.rb'
#cache_result = TomMemcache::get("load_sessions#{cookie_session_id}").freeze

session_id = JSON.parse(cookie_session_id)
dynamodb   = Aws::DynamoDB::Client.new(region: ENV['AWS_REGION'])
result     = { deactivation_code: nil, sessions: [], current_session_index: nil }

deactivation_code_thread = Thread.new {
  code = ''
  5.times { code << rand(9).to_s }

  deactivation_code_params = {
    table_name: 'DeactivationCodes',
    item: { google_id: session_id['google_id'], code: code, created_at: Time.now.to_s, attempts_made: 0 }
  }

  dynamodb.put_item(deactivation_code_params)
  result[:deactivation_code] = code
}

# @optimize @remember: need to optimze this

sessions_params = {
    table_name: 'Sessions',
    key_condition_expression: "#gid = :google_id",
    expression_attribute_names: {
        "#gid" => "google_id"
    },
    expression_attribute_values: {
        ":google_id" => session_id['google_id']
    }
}

begin
  session_index = 0
  query_result = dynamodb.query(sessions_params)
  query_result.items.each do |session|
    result[:current_session_index] = session_index if session['device_id'] == session_id['device_id']
    result[:sessions].push({
      device_type: session['user_agent'].match(/\((?<device>\w+)/)[:device],
      last_active: calculate_time_passed_in_words(Time.parse(session['last_updated'])),
      device_id:   session['device_id'],
      time_zone:   session['time_zone']
    })
    session_index = session_index + 1
  end
rescue Aws::DynamoDB::Errors::ServiceError => error
  print StatusCodeStr::BAD_REQUEST
end


deactivation_code_thread.join
result_to_json = result.to_json.freeze

TomMemcache::set("load_sessions#{cookie_session_id}", result_to_json, 30)
print "Content-type: application/json\n\n#{result_to_json}"
