#! /usr/bin/ruby

require_relative '../lib/tom_calendar.rb'


cookie_session_id = ENV['HTTP_COOKIE']&.split(';')&.find{ |cookie| cookie.match?('session_id') }&.sub('session_id=','')&.strip
cookie_session_id = nil if cookie_session_id == ''

unless cookie_session_id
  print StatusCodeStr::BAD_REQUEST
  return
end

session_id = JSON.parse(cookie_session_id)
dynamodb   = Aws::DynamoDB::Client.new(region: ENV['AWS_REGION'])

sessions_params = {
    table_name: 'Sessions',
    key_condition_expression: "#gid = :google_id",
    expression_attribute_names: {
        "#gid" => "google_id"
    },
    expression_attribute_values: {
        ":google_id" => session_id['google_id']
    }
}

begin
  query_result = dynamodb.query(sessions_params)
  query_result.items.each do |session|
    delete_params = {
     table_name: 'Sessions',
     key: { google_id: session['google_id'], device_id: session['device_id'] }
    }
    dynamodb.delete_item(delete_params) unless session['device_id'] == session_id['device_id']
  end
rescue Aws::DynamoDB::Errors::ServiceError => error
  print StatusCodeStr::BAD_REQUEST
end

print StatusCodeStr::OK
