#! /usr/bin/ruby

return %(Content-type: text/html


<html lang="en">
  <head>
    <title>Page Not Found</title>
    <div id="loading_screen" style="background-color:#FEFFFE;position:absolute;top:0px;left:0px;width:100%;height:100%;z-index:100;"></div>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
    <link rel="preload" as="style" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
  </head>
  <!-- <img src="https://tomcalendar.com/public/morty.gif" alt="morty.gif" style="width:1024px;height:512px;margin-top:64px;box-shadow: 0px 0px 25px black;"> -->
  <!-- <h1 style="font-size:10rem;margin-top:20vh;">404</h1> -->
  <h1>Page not found</h1>
  <p>The requested URL was not found on this server</p>
  <a href="/" style="text-decoration:none;color:#4285F4;font-size:3rem;position:absolute;bottom:1vh;right:1vh;text-align:right;">TomCalendar</a>
  <script>
    // background code
    const colors = ["#EA4335", "#FBBC05", "#34A853", "#4285F4"];
    const numBalls = 50;
    const balls = [];
    for (let i = 0; i < numBalls; i++) {
      let ball = document.createElement("div");
      ball.classList.add("ball");
      ball.style.background = colors[Math.floor(Math.random() * colors.length)];
      ball.style.left = `${Math.floor(Math.random() * 80)}vw`;
      ball.style.top = `${Math.floor(Math.random() * 80)}vh`;
      ball.style.transform = `scale(${Math.random()})`;
      ball.style.width = `${Math.random() * 18}em`;
      ball.style.height = ball.style.width;
      
      balls.push(ball);
      document.body.append(ball);
    }
    balls.forEach((el, i, ra) => {
      let to = {
        x: Math.random() * (i % 2 === 0 ? -11 : 11),
        y: Math.random() * 12
      };

      let anim = el.animate(
        [
          { transform: "translate(0, 0)" },
          { transform: `translate(${to.x}rem, ${to.y}rem)` }
        ],
        {
          duration: (Math.random() + 1) * 2000,
          direction: "alternate",
          fill: "both",
          iterations: Infinity,
          easing: "ease-in-out"
        }
      );
    });

    setTimeout(function() {
      document.getElementById("loading_screen").style.display = "none";
    }, 99);
  </script>
  <style type="text/css">
    html {
      background-color: #FEFFFE;
      font-family: 'Roboto', sans-serif;
      color: #0F1419;
      overflow: hidden;
      text-align: center;
      position absolute;
      width: 100%;
    }
    .ball {
      position: absolute;
      border-radius: 100%;
      opacity: 0.75;
      z-index: -1;
    }
    h1 {
      font-size: 7rem;
      font-weight: bold;
      color: #0F1419;
      text-shadow: 2px 3px 10px rgba(81,67,21,0.8);
      text-align: center;
      margin-top: 26vh;
    }
    p {
      text-align: center;
      font-size: 3.5rem;
      font-weight: normal;
      color: #0F1419;
      text-shadow: 2px 3px 10px rgba(81,67,21,0.8);
      margin-top: -2vh;
      //margin-bottom: 12vh;
    }
  </style>
</html>
)
