#! /usr/bin/ruby

  #<img src="https://tomcalendar.com/public/morty.gif" alt="morty.gif" style="width:512px;height:256px;margin-top:64px;">

print "Content-type: text/html\n\n"
print %(
<html lang="en">
  <title>Page Not Found</title>
  <head>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
    <link href="public/normalize.min.css" rel="stylesheet"/>
  </head>
  <img src="https://tomcalendar.com/public/morty.gif" alt="morty.gif" style="width:1024px;height:512px;margin-top:64px;box-shadow: 0px 0px 25px black;">
  <h1>The requested URL was not found on this server</h1>
  <style type="text/css">
    html {
      text-align: center;
      font-family: 'Roboto', sans-serif;
      font-size: 1.75vw;
    }
  </style>
</html>
)



