#! /usr/bin/ruby

return %(Content-type: text/html


<html lang="en">
  <head>
    <title>Page Not Found</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" rel="stylesheet"/>
  </head>
  <img src="https://tomcalendar.com/public/morty.gif" alt="morty.gif" style="width:1024px;height:512px;margin-top:64px;box-shadow: 0px 0px 25px black;">
  <h1>The requested URL was not found on this server</h1>
  <style type="text/css">
    html {
      text-align: center;
      font-family: 'Roboto', sans-serif;
      font-size: 1.75vw;
    }
  </style>
</html>
)
