#! /usr/bin/ruby

print "Content-type: text/html\n\n"
print %(
<html lang="en">
<body>
  <div id="root"></div>
  <script src="https://unpkg.com/react@16/umd/react.development.js"></script>
  <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
  <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>
  <script src="https://unpkg.com/@material-ui/core@latest/umd/material-ui.development.js"></script>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />


  <script type="text/babel">
    const { Button, Drawer, List, ListItem, ListItemAvatar, Avatar, ListItemText, ListItemIcon, Icon } = MaterialUI; // Components are available in MaterialUI object




    ReactDOM.render(





				<List>
					{['All mail', 'Trash', 'Spam'].map((text, index) => (
						<ListItem button key={text}>
							<ListItemIcon>{index % 2 === 0 ? <Icon>Inbox</Icon> : <Icon>Mail</Icon>}</ListItemIcon>
							<ListItemText primary={text} />
						</ListItem>
					))}
				</List>



    , document.querySelector('#root')
    );





  </script>


</body>
</html>
)










