#! /usr/bin/ruby

print "Content-type: text/html\n\n"
print %(
<html lang="en">

<body>
  <div id="root"></div>

  <!-- React -->
  <script src="https://unpkg.com/react@16/umd/react.development.js"></script>
  <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>

  <!-- Babel -->
  <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>

  <!-- MUI -->
  <script src="https://unpkg.com/@material-ui/core@latest/umd/material-ui.development.js"></script>

  <script type="text/babel">
    const { Button, List, ListItem, ListItemAvatar, Avatar, ListItemText } = MaterialUI; // Components are available in MaterialUI object

    ReactDOM.render(
    <List>
      <ListItem>
        <ListItemAvatar>
          <Avatar>
          </Avatar>
        </ListItemAvatar>
        <ListItemText primary="Example Timezone" secondary="current time" />
      </ListItem>
      <ListItem>
        <ListItemAvatar>
          <Avatar>
          </Avatar>
        </ListItemAvatar>
        <ListItemText primary="Example Timezone" secondary="Jan 7, 2014" />
      </ListItem>
      <ListItem>
        <ListItemAvatar>
          <Avatar>
          </Avatar>
        </ListItemAvatar>
        <ListItemText primary="Example Timezone" secondary="July 20, 2014" />
      </ListItem>
    </List>, 
      document.getElementById("root") 
    );
  </script>
</body>

</html>
)
