#! /usr/bin/ruby


`/home/ubuntu/tom_calendar/lib/tom_memcache/restart.sh >/dev/null &`

return %(Content-type: text/html


<html lang="en">
  <title>sssshhhhhhhh</title>
  <body>
    <h1>shhhhhhh</h1>
  </body>
  <script>
  </script>
  <style type="text/css">
    html {
      text-align: center;
    }
  </style>
</html>
)
