#! /usr/bin/ruby

other_user_google_id = TomEnv::get('QUERY_STRING')
other_user_google_id = other_user_google_id.split('=')[1]

is_logged_in = false
current_google_id = nil
session_id = get_session_id_from_cookies()

if session_id
  is_logged_in = true
  current_google_id = session_id['google_id']
end

user_agent_str = TomEnv::get('HTTP_USER_AGENT')&.downcase || ''
IS_DESKTOP = !( /phone|android/.match(user_agent_str) )

VW_FACTOR   = IS_DESKTOP ? 0.25 : 1
VH_FACTOR   = IS_DESKTOP ? 1 : 1
FONT_FACTOR = IS_DESKTOP ? 1.1 : 1

return %(Content-type: text/html


<html lang="en">
  <title>#{other_user_google_id}</title>
  <head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" rel="stylesheet"/>
    <script src="https://tomcalendar.com/public/react.production.min.js" crossorigin></script>
    <script src="https://tomcalendar.com/public/react-dom.production.min.js"></script>
    <script src="https://tomcalendar.com/public/material-ui.production.min.js"></script>
    <script src="https://tomcalendar.com/public/react_components.js?force_reload=#{rand(1000)}"></script>
    <script async src="https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAPS_API_KEY']}&libraries=places"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>
  <body onload="init();">
     <div class="event_feed" id="user_profile_event_feed" onscroll="onFeedScroll(this.id)">
       <div id="user_profile_image" align="center"></div>
       <div id="user_header_img">
         <img id="user_header_img_src" src="" style="height:12vh;max-width:33vw;visibility:hidden;">
       </div>
       <div id="user_profile_border"></div>
       <p id="user_profile_name_txt">Username</p>
       <div id="event_card_react_container_user_profile_0" style="margin-top:#{3 * VH_FACTOR}vh;"></div>
       <p id="user_profile_no_post_txt">No posts yet</p>
     </div>
  </body>
  <script>
    const IS_LOGGED_IN = #{is_logged_in};

    function init() {
    }
  </script>
  <style type="text/css">
  </style>
</html>
)
